#!/bin/bash
# LaTeX Installation Guide for macOS
# Save this as install_latex.sh and run with: bash install_latex.sh

echo "=== LaTeX Installation Options for macOS ==="
echo ""
echo "Option 1: Install MacTeX (Recommended - Full distribution)"
echo "Download from: https://www.tug.org/mactex/"
echo "Size: ~4GB, includes everything needed"
echo ""
echo "Option 2: Install BasicTeX (Minimal distribution)"
echo "Download from: https://www.tug.org/mactex/morepackages.html"
echo "Size: ~100MB, requires manual package installation"
echo ""
echo "Option 3: Install via Homebrew (if available)"
echo "brew install --cask mactex"
echo ""
echo "Option 4: Install TinyTeX (Minimal but smart)"
echo "brew install tinytex"
echo "tinytex::install_tinytex()"
echo ""
echo "=== After Installation ==="
echo "1. Restart your terminal"
echo "2. Run: pdflatex --version"
echo "3. Compile with: pdflatex presentation_aircraft_analysis.tex"
echo ""
echo "=== Required Packages for your presentation ==="
echo "Your presentation uses these LaTeX packages:"
echo "- beamer (presentation class)"
echo "- graphicx (for images)"
echo "- amsmath (for equations)"
echo "- booktabs (for tables)"
echo "- babel[italian] (for Italian language)"
echo "- inputenc[utf8] (for UTF-8 encoding)"
echo "- xcolor (for colors)"
echo ""
echo "All these are included in MacTeX and most distributions."
